[versions]
# Core Android & Compose
androidxCore = "1.15.0"
androidxLifecycle = "2.8.7"
androidxActivityCompose = "1.9.3"
androidxComposeBom = "2024.12.01"
androidxComposeCompiler = "1.5.8"

# Kotlin and KSP
coreKtx = "1.6.1"
datastorePreferences = "1.1.1"
integrity = "1.4.0"
junitKtx = "1.2.1"
kotlin = "1.9.22"
kotlinxCoroutinesTestVersion = "1.10.1"
ksp = "1.9.22-1.0.17"

# Google Services & Firebase
googleServices = "4.4.2"
firebase-bom = "33.7.0"

# Hilt
hiltAndroid = "2.50"
hiltAndroidCompiler = "2.50"
hiltAndroidGradlePlugin = "2.50"
hiltAndroidTesting = "2.50"
hiltNavigationCompose = "1.2.0"

# Material & UI
material = "1.12.0"

# Coroutines
coroutines = "1.7.3"
kotlinxCoroutinesAndroid = { version.ref = "coroutines" }
kotlinxCoroutinesPlayServices = { version.ref = "coroutines" }
kotlinxCoroutinesTest = { version.ref = "coroutines" }
kotlinxCoroutinesCore = { version.ref = "coroutines" }

# Testing
robolectric = "4.10.3"
shadowsFramework = "4.11.1"
testng = "7.10.2"
junit = "4.13.2"
mockk = "1.13.14"
truth = "1.4.4"
turbine = "1.2.0"

# Add Gradle plugin versions
agp = "8.7.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.7.6" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version = "23.1.0" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version = "25.1.1" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroidTesting" }
integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
kotlinx-coroutines-test-v1101 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTestVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
shadows-framework = { module = "org.robolectric:shadows-framework", version.ref = "shadowsFramework" }
testng = { group = "org.testng", name = "testng", version.ref = "testng" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
google-truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version = "2.2.0" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }